###
GET http://localhost:3000/

###
GET http://localhost:3000/listar/60e4a859a1c6e31d74341663

### Requisição correta!
POST http://localhost:3000/cadastrar
Content-Type: application/json

{
	"dono": "Bruna",
	"placamae": "a",
	"processador": "a",
    "memoria": 1,
    "armazenamento": "a",
    "fonte": "a",
    "criadoEm": "2021-04-04" 
}



### Requisição com erro
POST http://localhost:3000/ciclo/cadastrar
Content-Type: application/json

{
	"creditos": [
		{
			"nome": "Salário",
			"valor": 5000
		},
		{
			"nome": "Investimento",
			"valor": 50
		}
	],
	"debitos": [
		{
			"nome": "Luz",
			"valor": 300,
			"status": "PAGO"
		},
		{
			"nome": "Água",
			"valor": 150,
			"status": "AGENDADO"
		}
	]
}

# {
# 	"data": "O campo data é obrigatório!",
# 	"valor": "O campo valor é obrigatório"
# }